import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { addOrder } from '../services/orderService';
import { getAllClothingItems } from '../services/clothingItemService';

function CreateOrderForm() {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [clothingItems, setClothingItems] = useState([]);
  const [loadingClothingItems, setLoadingClothingItems] = useState(true);
  
  // Order ID will be generated by the backend in sequential format (ORD-1000, ORD-1001, etc.)
  
  useEffect(() => {
    const fetchClothingItems = async () => {
      try {
        setLoadingClothingItems(true);
        const response = await getAllClothingItems();
        if (response.success && response.data) {
          setClothingItems(response.data);
        } else {
          console.error('Failed to load clothing items');
        }
      } catch (err) {
        console.error('Error fetching clothing items:', err);
      } finally {
        setLoadingClothingItems(false);
      }
    };

    fetchClothingItems();
  }, []);

  // Get default item from clothing items if available
  const defaultItem = clothingItems.length > 0 ? clothingItems[0] : null;
  
  const [formData, setFormData] = useState({
    // order_id will be generated by the backend
    order_Date: new Date().toISOString().split('T')[0], // Today's date
    customer_Name: '',
    order_type: 'sales_Order',
    email: '',
    contact_No: '',
    order_Status: 'CONFIRMED',
    description: '',
    sub_Total: defaultItem ? defaultItem.price : 0,
    order_Items: [{ 
      product_Name: defaultItem ? defaultItem.name : '', 
      quantity: 1, 
      price: defaultItem ? defaultItem.price : 0,
      size: '',
      color: ''
    }],
    delivery_Address: {
      street: '',
      city: '',
      district: ''
    }
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    
    // Handle nested delivery_Address fields
    if (name.startsWith('delivery_')) {
      const field = name.replace('delivery_', '');
      setFormData({
        ...formData,
        delivery_Address: {
          ...formData.delivery_Address,
          [field]: value
        }
      });
    } else {
      setFormData({
        ...formData,
        [name]: value
      });
    }
  };

  const handleItemChange = (index, field, value) => {
    const updatedItems = [...formData.order_Items];
    
    // If the field is product_Name and we're selecting from dropdown
    if (field === 'product_Name') {
      // Find the selected clothing item
      const selectedItem = clothingItems.find(item => item.name === value);
      
      // If an item was found, update its price automatically
      if (selectedItem) {
        updatedItems[index] = {
          ...updatedItems[index],
          [field]: value,
          price: selectedItem.price
        };
      } else {
        updatedItems[index] = {
          ...updatedItems[index],
          [field]: value
        };
      }
    } else {
      updatedItems[index] = {
        ...updatedItems[index],
        [field]: field === 'quantity' || field === 'price' ? Number(value) : value
      };
    }
    
    // Recalculate subtotal whenever items change
    const subTotal = updatedItems.reduce((total, item) => {
      return total + (item.quantity * item.price);
    }, 0);
    
    setFormData({
      ...formData,
      order_Items: updatedItems,
      sub_Total: subTotal
    });
  };

  const addOrderItem = () => {
    // Default to the first clothing item in the list if available
    const defaultItem = clothingItems.length > 0 ? clothingItems[0] : null;
    
    setFormData({
      ...formData,
      order_Items: [
        ...formData.order_Items, 
        { 
          product_Name: defaultItem ? defaultItem.name : '', 
          quantity: 1, 
          price: defaultItem ? defaultItem.price : 0 
        }
      ]
    });
  };

  const removeOrderItem = (index) => {
    if (formData.order_Items.length > 1) {
      const updatedItems = formData.order_Items.filter((_, i) => i !== index);
      
      // Recalculate subtotal after removing item
      const subTotal = updatedItems.reduce((total, item) => {
        return total + (item.quantity * item.price);
      }, 0);
      
      setFormData({
        ...formData,
        order_Items: updatedItems,
        sub_Total: subTotal
      });
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError(null);

    try {
      await addOrder(formData);
      navigate('/orders'); // Redirect to order list page after successful creation
    } catch (err) {
      console.error('Error creating order:', err);
      setError('Failed to create order. Please check your inputs and try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="container mx-auto px-4 py-8 max-w-5xl">
      <div className="flex items-center justify-between mb-8">
        <h1 className="text-3xl font-bold text-gray-800">
          <span className="text-blue-600">Create</span> New Order
        </h1>
        <button
          type="button"
          onClick={() => navigate('/')}
          className="flex items-center bg-gray-100 hover:bg-gray-200 text-gray-700 py-2 px-4 rounded-lg transition duration-200"
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-1" viewBox="0 0 20 20" fill="currentColor">
            <path fillRule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clipRule="evenodd" />
          </svg>
          Back to Orders
        </button>
      </div>

      {error && (
        <div className="bg-red-100 border-l-4 border-red-500 text-red-700 p-4 mb-6 rounded-lg animate-pulse">
          <div className="flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
              <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
            </svg>
            {error}
          </div>
        </div>
      )}

      <form onSubmit={handleSubmit} className="bg-white shadow-lg rounded-lg px-8 pt-6 pb-8 mb-4 border border-gray-100">
        <div className="bg-blue-50 -mx-8 px-8 py-3 mb-6 border-b border-blue-100">
          <h2 className="text-xl font-semibold text-blue-800">Order Information</h2>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          
          {/* Order Date */}
          <div className="mb-4">
  <label
    className="block text-gray-700 text-sm font-semibold mb-2"
    htmlFor="order_Date"
  >
    Order Date
  </label>
  <input
    className="shadow-sm appearance-none border border-gray-200 rounded w-full py-3 px-4 text-gray-700 bg-gray-100 leading-tight focus:outline-none cursor-not-allowed"
    id="order_Date"
    name="order_Date"
    type="date"
    value={new Date().toISOString().split("T")[0]} // ✅ always today
    readOnly // ✅ prevents manual editing
    required
  />
</div>

          {/* Customer Name */}
          <div className="mb-4">
            <label className="block text-gray-700 text-sm font-semibold mb-2" htmlFor="customer_Name">
              Customer Name
            </label>
            <div className="relative">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
                  <path fillRule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clipRule="evenodd" />
                </svg>
              </div>
              <input
                className="shadow-sm appearance-none border border-gray-200 rounded w-full py-3 pl-10 px-4 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:border-blue-500"
                id="customer_Name"
                name="customer_Name"
                type="text"
                placeholder="John Doe"
                value={formData.customer_Name}
                onChange={handleChange}
                required
              />
            </div>
          </div>

          {/* Order Type */}
          <div className="mb-4">
            <label className="block text-gray-700 text-sm font-semibold mb-2" htmlFor="order_type">
              Order Type
            </label>
            <div className="relative">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
                  <path d="M8 5a1 1 0 100 2h5.586l-1.293 1.293a1 1 0 001.414 1.414l3-3a1 1 0 000-1.414l-3-3a1 1 0 10-1.414 1.414L13.586 5H8zM12 15a1 1 0 100-2H6.414l1.293-1.293a1 1 0 10-1.414-1.414l-3 3a1 1 0 000 1.414l3 3a1 1 0 001.414-1.414L6.414 15H12z" />
                </svg>
              </div>
              <select
                className="shadow-sm appearance-none border border-gray-200 rounded w-full py-3 pl-10 px-4 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:border-blue-500"
                id="order_type"
                name="order_type"
                value={formData.order_type}
                onChange={handleChange}
                required
              >
                <option value="sales_Order">Sales Order</option>
                <option value="purchase_Order">Purchase Order</option>
              </select>
              <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                <svg className="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                  <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
                </svg>
              </div>
            </div>
          </div>

          {/* Email */}
          <div className="mb-4">
            <label className="block text-gray-700 text-sm font-semibold mb-2" htmlFor="email">
              Email
            </label>
            <div className="relative">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
                  <path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z" />
                  <path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z" />
                </svg>
              </div>
              <input
                className="shadow-sm appearance-none border border-gray-200 rounded w-full py-3 pl-10 px-4 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:border-blue-500"
                id="email"
                name="email"
                type="email"
                placeholder="example@example.com"
                value={formData.email}
                onChange={handleChange}
                required
              />
            </div>
          </div>

          {/* Contact Number */}
          <div className="mb-4">
            <label className="block text-gray-700 text-sm font-semibold mb-2" htmlFor="contact_No">
              Contact Number
            </label>
            <div className="relative">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
                  <path d="M2 3a1 1 0 011-1h2.153a1 1 0 01.986.836l.74 4.435a1 1 0 01-.54 1.06l-1.548.773a11.037 11.037 0 006.105 6.105l.774-1.548a1 1 0 011.059-.54l4.435.74a1 1 0 01.836.986V17a1 1 0 01-1 1h-2C7.82 18 2 12.18 2 5V3z" />
                </svg>
              </div>
              <input
                className="shadow-sm appearance-none border border-gray-200 rounded w-full py-3 pl-10 px-4 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:border-blue-500"
                id="contact_No"
                name="contact_No"
                type="text"
                placeholder="(+94) 123 456 789"
                value={formData.contact_No}
                onChange={handleChange}
                required
              />
            </div>
          </div>

         {/* ✅ Order Status (Auto-set to CONFIRMED, not editable) */}
        <div className="mb-4">
  <label
    className="block text-gray-700 text-sm font-semibold mb-2"
    htmlFor="order_Status"
  >
    Order Status
  </label>
  <input
    className="shadow-sm appearance-none border border-gray-200 rounded w-full py-3 px-4 text-gray-700 bg-gray-100 leading-tight focus:outline-none cursor-not-allowed"
    id="order_Status"
    name="order_Status"
    type="text"
    value="CONFIRMED"   // ✅ always confirmed
    readOnly            // ✅ not editable
    required
  />
</div>


          {/* Description */}
          <div className="mb-4 md:col-span-2">
            <label className="block text-gray-700 text-sm font-semibold mb-2" htmlFor="description">
              Description (Optional)
            </label>
            <div className="relative">
              <div className="absolute top-3 left-3 flex items-start pointer-events-none">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
                  <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
                </svg>
              </div>
              <textarea
                className="shadow-sm appearance-none border border-gray-200 rounded w-full py-3 pl-10 px-4 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:border-blue-500"
                id="description"
                name="description"
                placeholder="Enter any additional notes about this order..."
                value={formData.description}
                onChange={handleChange}
                rows="3"
              />
            </div>
          </div>
        </div>

        {/* Delivery Address */}
        <div className="mb-8">
          <div className="bg-blue-50 -mx-8 px-8 py-3 mb-6 border-b border-blue-100 border-t">
            <h2 className="text-xl font-semibold text-blue-800">Delivery Address</h2>
            <p className="text-sm text-blue-600">Where should this order be delivered?</p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="mb-4">
              <label className="block text-gray-700 text-sm font-semibold mb-2" htmlFor="delivery_street">
                Street
              </label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
                    <path fillRule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clipRule="evenodd" />
                  </svg>
                </div>
                <input
                  className="shadow-sm appearance-none border border-gray-200 rounded w-full py-3 pl-10 px-4 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:border-blue-500"
                  id="delivery_street"
                  name="delivery_street"
                  type="text"
                  placeholder="123 Main St,"
                  value={formData.delivery_Address.street}
                  onChange={handleChange}
                  required
                />
              </div>
            </div>

            <div className="mb-4">
              <label className="block text-gray-700 text-sm font-semibold mb-2" htmlFor="delivery_city">
                City
              </label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
                    <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z" />
                  </svg>
                </div>
                <input
                  className="shadow-sm appearance-none border border-gray-200 rounded w-full py-3 pl-10 px-4 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:border-blue-500"
                  id="delivery_city"
                  name="delivery_city"
                  type="text"
                  placeholder="Malabe"
                  value={formData.delivery_Address.city}
                  onChange={handleChange}
                  required
                />
              </div>
            </div>

            <div className="mb-4">
              <label className="block text-gray-700 text-sm font-semibold mb-2" htmlFor="delivery_district">
                District
              </label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
                    <path d="M7 3a1 1 0 000 2h6a1 1 0 100-2H7zM4 7a1 1 0 011-1h10a1 1 0 110 2H5a1 1 0 01-1-1zM2 11a2 2 0 012-2h12a2 2 0 012 2v4a2 2 0 01-2 2H4a2 2 0 01-2-2v-4z" />
                  </svg>
                </div>
                <input
                  className="shadow-sm appearance-none border border-gray-200 rounded w-full py-3 pl-10 px-4 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:border-blue-500"
                  id="delivery_district"
                  name="delivery_district"
                  type="text"
                  placeholder="Colombo"
                  value={formData.delivery_Address.district}
                  onChange={handleChange}
                  required
                />
              </div>
            </div>
          </div>
        </div>

        {/* Order Items */}
        <div className="mb-8">
          <div className="bg-blue-50 -mx-8 px-8 py-3 mb-6 border-b border-blue-100 border-t">
            <div className="flex justify-between items-center">
              <div>
                <h2 className="text-xl font-semibold text-blue-800">Order Items</h2>
                <p className="text-sm text-blue-600">Add products to this order</p>
              </div>
              <button
                type="button"
                onClick={addOrderItem}
                className="bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-4 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50 transition duration-200 flex items-center"
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-1" viewBox="0 0 20 20" fill="currentColor">
                  <path fillRule="evenodd" d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z" clipRule="evenodd" />
                </svg>
                Add Item
              </button>
            </div>
          </div>
          
          {/* Available Clothing Items */}
          <div className="mb-6 bg-gray-50 p-4 rounded-lg border border-gray-200">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-medium text-gray-800 flex items-center">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2 text-blue-600" viewBox="0 0 20 20" fill="currentColor">
                  <path fillRule="evenodd" d="M10 2a4 4 0 00-4 4v1H5a1 1 0 00-.994.89l-1 9A1 1 0 004 18h12a1 1 0 00.994-1.11l-1-9A1 1 0 0015 7h-1V6a4 4 0 00-4-4zm2 5V6a2 2 0 10-4 0v1h4zm-6 3a1 1 0 112 0 1 1 0 01-2 0zm7-1a1 1 0 100 2 1 1 0 000-2z" clipRule="evenodd" />
                </svg>
                Available Clothing Items
              </h3>
              <div className="text-sm text-blue-600 font-medium flex items-center">
                <span>Click item to select or</span>
                <div className="relative ml-2 inline-block">
                  <div className="group">
                    <button type="button" className="text-blue-700 hover:text-blue-900 font-semibold underline flex items-center">
                      Add New Item +
                    </button>
                    <div className="absolute z-10 right-0 mt-2 hidden group-hover:block">
                      <div className="bg-white p-3 rounded-lg shadow-lg border border-gray-200 w-48">
                        <p className="text-xs text-gray-600 mb-2">Add new item with:</p>
                        {clothingItems.map(item => (
                          <button
                            key={item.id}
                            type="button"
                            className="block w-full text-left px-2 py-1 text-sm hover:bg-blue-50 rounded"
                            onClick={() => {
                              // Add a new order item with this product
                              const updatedItems = [
                                ...formData.order_Items,
                                { product_Name: item.name, quantity: 1, price: item.price }
                              ];
                              
                              const subTotal = updatedItems.reduce((total, item) => {
                                return total + (item.quantity * item.price);
                              }, 0);
                              
                              setFormData({
                                ...formData,
                                order_Items: updatedItems,
                                sub_Total: subTotal
                              });
                            }}
                          >
                            {item.name} - ${item.price.toFixed(2)}
                          </button>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
              {clothingItems.map(item => (
                <div 
                  key={item.id} 
                  className={`bg-white p-3 rounded border ${
                    formData.order_Items.length > 0 && formData.order_Items[0].product_Name === item.name
                      ? 'border-blue-500 shadow-md'
                      : 'border-gray-200 hover:border-blue-400 hover:shadow-md'
                  } transition-all duration-200 flex flex-col items-center text-center cursor-pointer`}
                  onClick={() => {
                    // If there are any existing items in the order, update the first one
                    if (formData.order_Items.length > 0) {
                      handleItemChange(0, 'product_Name', item.name);
                      
                      // Show a brief visual feedback
                      const el = document.activeElement;
                      if (el) el.blur();
                    }
                  }}
                >
                  <span className="text-sm font-medium mb-1">{item.name}</span>
                  <span className="bg-blue-100 text-blue-700 px-3 py-1 rounded-full text-sm font-bold">${item.price.toFixed(2)}</span>
                  {formData.order_Items.length > 0 && formData.order_Items[0].product_Name === item.name && (
                    <span className="mt-2 text-xs text-green-600 flex items-center">
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 mr-1" viewBox="0 0 20 20" fill="currentColor">
                        <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                      </svg>
                      Selected
                    </span>
                  )}
                </div>
              ))}
            </div>
          </div>

          {formData.order_Items.map((item, index) => (
            <div key={index} className="mb-6 border border-gray-200 p-5 rounded-lg shadow-sm hover:shadow-md transition duration-200">
              <div className="flex justify-between items-center mb-4">
                <h3 className="text-lg font-semibold text-gray-800 flex items-center">
                  <span className="bg-blue-100 text-blue-800 text-sm font-medium px-3 py-1 rounded-full mr-2">
                    #{index + 1}
                  </span>
                  Item Details
                </h3>
                <button
                  type="button"
                  onClick={() => removeOrderItem(index)}
                  className={`text-red-500 hover:text-red-700 font-medium flex items-center ${formData.order_Items.length === 1 ? 'opacity-50 cursor-not-allowed' : 'hover:bg-red-50'} px-3 py-1 rounded transition duration-200`}
                  disabled={formData.order_Items.length === 1}
                >
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-1" viewBox="0 0 20 20" fill="currentColor">
                    <path fillRule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clipRule="evenodd" />
                  </svg>
                  Remove
                </button>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="mb-2">
                  <label className="block text-gray-700 text-sm font-semibold mb-2">
                    Product Name
                  </label>
                  <div className="relative">
                    <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
                        <path fillRule="evenodd" d="M10 2a4 4 0 00-4 4v1H5a1 1 0 00-.994.89l-1 9A1 1 0 004 18h12a1 1 0 00.994-1.11l-1-9A1 1 0 0015 7h-1V6a4 4 0 00-4-4zm2 5V6a2 2 0 10-4 0v1h4zm-6 3a1 1 0 112 0 1 1 0 01-2 0zm7-1a1 1 0 100 2 1 1 0 000-2z" clipRule="evenodd" />
                      </svg>
                    </div>
                    <select
                      className="shadow-sm appearance-none border border-gray-200 rounded w-full py-3 pl-10 px-4 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:border-blue-500"
                      value={item.product_Name}
                      onChange={(e) => handleItemChange(index, 'product_Name', e.target.value)}
                      required
                    >
                      {clothingItems.map(clothing => (
                        <option key={clothing.id} value={clothing.name}>
                          {clothing.name} - ${clothing.price.toFixed(2)}
                        </option>
                      ))}
                    </select>
                    <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                      <svg className="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                        <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
                      </svg>
                    </div>
                  </div>
                </div>

                <div className="mb-2">
                  <label className="block text-gray-700 text-sm font-semibold mb-2">
                    Size
                  </label>
                  <div className="relative">
                    <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
                        <path d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM14 11a1 1 0 011 1v1h1a1 1 0 110 2h-1v1a1 1 0 11-2 0v-1h-1a1 1 0 110-2h1v-1a1 1 0 011-1z" />
                      </svg>
                    </div>
                    <select
                      className="shadow-sm appearance-none border border-gray-200 rounded w-full py-3 pl-10 px-4 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:border-blue-500"
                      value={item.size}
                      onChange={(e) => handleItemChange(index, 'size', e.target.value)}
                      required
                    >
                      <option value="">Select Size</option>
                      {clothingItems
                        .find(clothing => clothing.name === item.product_Name)?.sizes?.map(size => (
                          <option key={size} value={size}>{size}</option>
                        )) || ['XS', 'S', 'M', 'L', 'XL', 'XXL'].map(size => (
                          <option key={size} value={size}>{size}</option>
                        ))
                      }
                    </select>
                    <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                      <svg className="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                        <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
                      </svg>
                    </div>
                  </div>
                </div>

                <div className="mb-2">
                  <label className="block text-gray-700 text-sm font-semibold mb-2">
                    Color
                  </label>
                  <div className="relative">
                    <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
                        <path fillRule="evenodd" d="M4 2a2 2 0 00-2 2v11a3 3 0 106 0V4a2 2 0 00-2-2H4zm1 14a1 1 0 100-2 1 1 0 000 2zm5-1.757l4.9-4.9a2 2 0 000-2.828L13.485 5.1a2 2 0 00-2.828 0L10 5.757v8.486zM16 18H9.071l6-6H16a2 2 0 012 2v2a2 2 0 01-2 2z" clipRule="evenodd" />
                      </svg>
                    </div>
                    <select
                      className="shadow-sm appearance-none border border-gray-200 rounded w-full py-3 pl-10 px-4 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:border-blue-500"
                      value={item.color}
                      onChange={(e) => handleItemChange(index, 'color', e.target.value)}
                      required
                    >
                      <option value="">Select Color</option>
                      {clothingItems
                        .find(clothing => clothing.name === item.product_Name)?.colors?.map(color => (
                          <option key={color} value={color}>{color}</option>
                        )) || ['Black', 'White', 'Blue','Grey', 'Red', 'Green'].map(color => (
                          <option key={color} value={color}>{color}</option>
                        ))
                      }
                    </select>
                    <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                      <svg className="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                        <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
                      </svg>
                    </div>
                  </div>
                </div>

                <div className="mb-2">
                  <label className="block text-gray-700 text-sm font-semibold mb-2">
                    Quantity
                  </label>
                  <div className="relative">
                    <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
                        <path d="M3 1a1 1 0 000 2h1.22l.305 1.222a.997.997 0 00.01.042l1.358 5.43-.893.892C3.74 11.846 4.632 14 6.414 14H15a1 1 0 000-2H6.414l1-1H14a1 1 0 00.894-.553l3-6A1 1 0 0017 3H6.28l-.31-1.243A1 1 0 005 1H3zM16 16.5a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0zM6.5 18a1.5 1.5 0 100-3 1.5 1.5 0 000 3z" />
                      </svg>
                    </div>
                    <input
                      className="shadow-sm appearance-none border border-gray-200 rounded w-full py-3 pl-10 px-4 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:border-blue-500"
                      type="number"
                      min="1"
                      value={item.quantity}
                      onChange={(e) => handleItemChange(index, 'quantity', e.target.value)}
                      required
                    />
                  </div>
                </div>

                <div className="mb-2">
                  <label className="block text-gray-700 text-sm font-semibold mb-2">
                    Price
                  </label>
                  <div className="relative">
                    <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
                        <path d="M8.433 7.418c.155-.103.346-.196.567-.267v1.698a2.305 2.305 0 01-.567-.267C8.07 8.34 8 8.114 8 8c0-.114.07-.34.433-.582zM11 12.849v-1.698c.22.071.412.164.567.267.364.243.433.468.433.582 0 .114-.07.34-.433.582a2.305 2.305 0 01-.567.267z" />
                        <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-13a1 1 0 10-2 0v.092a4.535 4.535 0 00-1.676.662C6.602 6.234 6 7.009 6 8c0 .99.602 1.765 1.324 2.246.48.32 1.054.545 1.676.662v1.941c-.391-.127-.68-.317-.843-.504a1 1 0 10-1.51 1.31c.562.649 1.413 1.076 2.353 1.253V15a1 1 0 102 0v-.092a4.535 4.535 0 001.676-.662C13.398 13.766 14 12.991 14 12c0-.99-.602-1.765-1.324-2.246A4.535 4.535 0 0011 9.092V7.151c.391.127.68.317.843.504a1 1 0 101.511-1.31c-.563-.649-1.413-1.076-2.354-1.253V5z" clipRule="evenodd" />
                      </svg>
                    </div>
                    <input
                      className="shadow-sm appearance-none border border-gray-200 rounded w-full py-3 pl-10 px-4 text-gray-700 bg-gray-50 leading-tight focus:outline-none focus:shadow-outline focus:border-blue-500"
                      type="number"
                      min="0"
                      step="0.01"
                      value={item.price}
                      readOnly
                      required
                    />
                    <div className="absolute right-0 top-0 h-full flex items-center pr-3">
                      <span className="text-sm text-blue-600 font-medium">Auto-calculated</span>
                    </div>
                  </div>
                </div>
              </div>

              <div className="mt-4 flex justify-end">
                <div className="bg-blue-50 text-blue-700 font-semibold py-2 px-4 rounded-lg">
                  Item Total: ${(item.quantity * item.price).toFixed(2)}
                </div>
              </div>
            </div>
          ))}
        </div>

        

        {/* Order Summary */}
        <div className="mb-6">
          <div className="bg-blue-50 -mx-8 px-8 py-3 mb-6 border-b border-blue-100 border-t">
            <h2 className="text-xl font-semibold text-blue-800">Order Summary</h2>
          </div>
          
          <div className="bg-gray-50 p-6 rounded-lg border border-gray-200 shadow-inner">
            <div className="flex justify-between items-center mb-2">
              <span className="text-gray-600">Items:</span>
              <span>{formData.order_Items.length}</span>
            </div>
            <div className="flex justify-between items-center mb-2">
              <span className="text-gray-600">Total Quantity:</span>
              <span>{formData.order_Items.reduce((sum, item) => sum + Number(item.quantity), 0)} items</span>
            </div>
            <div className="border-t border-dashed border-gray-300 my-3"></div>
            <div className="flex justify-between items-center text-lg font-bold text-blue-700">
              <span>Order Total:</span>
              <span>${formData.sub_Total.toFixed(2)}</span>
            </div>
          </div>
        </div>

        

        {/* Submit Button */}
        <div className="flex items-center justify-between pt-4 border-t border-gray-200">
          <button
            type="button"
            onClick={() => navigate('/')}
            className="bg-white border border-gray-300 hover:bg-gray-100 text-gray-700 font-medium py-3 px-6 rounded-lg focus:outline-none focus:ring-2 focus:ring-gray-300 focus:ring-opacity-50 transition duration-200 flex items-center"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-1" viewBox="0 0 20 20" fill="currentColor">
              <path fillRule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clipRule="evenodd" />
            </svg>
            Cancel
          </button>
          <button
            type="submit"
            className="bg-blue-600 hover:bg-blue-700 text-white font-medium py-3 px-8 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50 transition duration-200 flex items-center shadow-sm"
            disabled={loading}
          >
            {loading ? (
              <>
                <svg className="animate-spin -ml-1 mr-2 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                Creating...
              </>
            ) : (
              <>
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-1" viewBox="0 0 20 20" fill="currentColor">
                  <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                </svg>
                Create Order
              </>
            )}
          </button>
        </div>

        
      </form>
    </div>

    
  );
}

export default CreateOrderForm;
